Fixed ``python`` on Ubuntu
zeldaret/ph pull request #21
Opened 2024-04-09 15:33 UTC by Yanis42

On Windows you can use python from ``python`` but on Linux (and mac too?) it's ``python3``, though the default version on Ubuntu is 3.10, so you need to install it from ``apt-get install python3.11`` then run ``python3.11 file.py``, I tried using an alias but it didn't work so instead I just made an env variable that you can override when needed

Not sure how it works for you but it should make it build properly on Linux (tested on WSL2), also idk if that's a solid fix

2024-04-10 21:35 UTC, AetiasHax requested changes
Nice touch! But I noticed that it still runs `python` and not `python3.11` on non-Windows systems, see my comment above.

2024-04-10 21:35 UTC, AetiasHax commented on Makefile
>  endif
Line 17 can't assign to `PYTHON` due to the initial assignment on line 11. Moving line 11 to be below the `endif` should work?

2024-04-10 23:47 UTC, Yanis42 commented on Makefile
>  endif
should be good now

2024-04-11 15:50 UTC, AetiasHax approved these changes

2024-04-11 15:50 UTC, merged