Add additional item IDs
zeldaret/ph pull request #4
Opened 2024-01-08 02:40 UTC by mike8699

Hi there, I'm one of the devs working on the [phantom hourglass randomizer](https://github.com/phst-randomizer/ph-randomizer). I noticed you are enumerating the item IDs so I went ahead and added a bunch of missing ones that we've documented during the course of developing the randomizer. Hope this helps!

2024-01-08 19:10 UTC, AetiasHax requested changes
Thanks a ton! I got word of the randomizer recently, and from your PH docs, I noticed that the Player struct (0x021BA4DC) corresponds with the ItemManager class in this repo. So, I shamelessly copied over what was missing in ItemManager from your docs. Please feel free to copy it back. 😉

Anyway, there's a small error near the shape crystals; they're all named the same. Fix it when you have the time!

2024-01-08 19:10 UTC, AetiasHax commented on include/Item.hpp
> +    ItemId_SquareCrystal = 35,
The triangle and circle crystals are missing here!

2024-01-14 16:56 UTC, mike8699 commented on include/Item.hpp
> +    ItemId_SquareCrystal = 35,
Whoops 😅

2024-01-14 16:56 UTC, mike8699 commented on include/Item.hpp
> +    ItemId_SquareCrystal = 35,
Fixed!

2024-01-16 15:13 UTC, merged